### ISSUE TITLE
Data License and Code License

### ISSUE THREAD

**Issue by LukvonStrom** [castor-software/Duets#2]
Dear Duets Maintainers,

thank you very much for this Dataset! I have been looking for something like this and was actually contemplating building it myself. 
For me to be able to use it though it would be very helpful if you could specify the license of the Data and of the Code within this repository.

Thank you very much in advance!

Kind regards,
Lukas

**Comment by LukvonStrom** [comment]
Also in a related question, would you be able to upload the final dataset to huggingface/kaggle?

**Comment by cesarsotovalero** [comment]
Hi @LukvonStrom, thanks for reaching out. This project is MIT licensed, [I've added it just now](https://github.com/ASSERT-KTH/Duets/blob/master/LICENSE.md). You're free to use the code and dataset for your purposes.

The final datased is in Zenodo: [https://zenodo.org/records/4723387](https://zenodo.org/records/4723387)

@tdurieux Would you like to upload it also to Kaggle?

**Comment by tdurieux** [comment]
We could submit it on Kaggle if you see a usage there.

**Comment by cesarsotovalero** [comment]
> We could submit it on Kaggle if you see a usage there.

@tdurieux Here is it: [https://www.kaggle.com/datasets/cesarsoto/duets-395-java-libraries-and-their-2874-clients](https://www.kaggle.com/datasets/cesarsoto/duets-395-java-libraries-and-their-2874-clients)
